# Generated by Django 3.2.8 on 2021-11-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bet_category_comment_lot_notification_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='state',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='state',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(),
        ),
    ]
