# Generated by Django 3.2.8 on 2021-11-13 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211113_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='currency',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='auctions.currency'),
            preserve_default=False,
        ),
    ]
