# Generated by Django 3.2.8 on 2021-11-13 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20211113_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='currency',
            field=models.OneToOneField(default='USD', on_delete=django.db.models.deletion.CASCADE, to='auctions.currency'),
        ),
    ]
