# Generated by Django 3.2.8 on 2021-11-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_lot_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='currency',
            field=models.ForeignKey(default='USD', on_delete=django.db.models.deletion.CASCADE, to='auctions.currency'),
        ),
    ]
