# Generated by Django 3.2.8 on 2021-11-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20211122_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
